### ISSUE TITLE
SpoutReceiver  receive a Invert Image

### ISSUE THREAD

**Issue by hepra** [fg-uulm/cef-spout#2]
![image](https://user-images.githubusercontent.com/15621729/103741405-f5a94f00-5033-11eb-932c-d653a0f41658.png)
I don't know  how to  invert this

**Comment by hepra** [comment]
![image](https://user-images.githubusercontent.com/15621729/103742279-846a9b80-5035-11eb-9255-baea9e0730fc.png)
I set this to  false  and  got a correct result 
thanks  for you  build  this project ~

**Comment by fg-uulm** [comment]
hi @hepra, thanks for providing your fix - although not sure what causes this in the beginning :/ closing for now as it seems to be more of a settings thing than an actual bug.
